"""
Synthetic Healthcare Data Generator
====================================
Generates realistic fake patient records for SMPC demonstration.

All data generated by this module is SYNTHETIC/FAKE and should
never be confused with real patient data. Each record is clearly
labeled with a synthetic flag.

Fields generated:
    - patient_id: Unique identifier
    - name: Fake patient name
    - age: Random age (18-90)
    - gender: M/F/Other
    - blood_pressure_systolic: 90-180 mmHg
    - blood_pressure_diastolic: 60-120 mmHg
    - glucose_level: 70-200 mg/dL
    - heart_rate: 55-110 bpm
    - cholesterol: 120-300 mg/dL
    - bmi: 18.0-40.0
    - diagnosis_code: ICD-10 code
    - diagnosis_description: Human-readable diagnosis
    - insurance_id: Fake insurance identifier
    - admission_date: Random date in past year
    - is_synthetic: Always True (clearly labeled)
"""

import json
import os
import random
import time
from typing import List, Dict, Optional
from datetime import datetime, timedelta

# Try to import Faker; provide fallback
try:
    from faker import Faker
    _FAKER_AVAILABLE = True
except ImportError:
    _FAKER_AVAILABLE = False


# Common ICD-10 diagnosis codes for simulation
ICD10_CODES = [
    ("I10", "Essential (primary) hypertension"),
    ("E11", "Type 2 diabetes mellitus"),
    ("J06.9", "Acute upper respiratory infection, unspecified"),
    ("M54.5", "Low back pain"),
    ("J18.9", "Pneumonia, unspecified organism"),
    ("K21.0", "Gastro-esophageal reflux disease with esophagitis"),
    ("E78.5", "Hyperlipidemia, unspecified"),
    ("F32.9", "Major depressive disorder, single episode, unspecified"),
    ("J45.909", "Unspecified asthma, uncomplicated"),
    ("N39.0", "Urinary tract infection, site not specified"),
    ("I25.10", "Atherosclerotic heart disease of native coronary artery"),
    ("E03.9", "Hypothyroidism, unspecified"),
    ("G43.909", "Migraine, unspecified, not intractable"),
    ("J20.9", "Acute bronchitis, unspecified"),
    ("K58.9", "Irritable bowel syndrome without diarrhea"),
]

PARTY_NAMES = {
    "party_a": "Hospital A — City General Medical Center",
    "party_b": "Hospital B — Regional Healthcare Institute",
    "party_c": "Insurance Co — National Health Insurance Corp",
    "party_d": "Hospital D — University Medical Hospital",
    "party_e": "Hospital E — Community Health Center",
    "party_f": "Hospital F — Metro General Hospital",
    "party_g": "Hospital G — Rural Health Clinic",
    "party_h": "Hospital H — Pediatric Medical Center",
    "party_i": "Hospital I — Veterans Affairs Hospital",
    "party_j": "Hospital J — Emergency Care Network",
}

# Generate dynamic party IDs for any count
_PARTY_LETTERS = list("abcdefghijklmnopqrstuvwxyz")


def _generate_name(fake=None) -> str:
    """Generate a fake patient name."""
    if fake and _FAKER_AVAILABLE:
        return fake.name()
    first_names = ["John", "Jane", "Alice", "Bob", "Carol", "David", "Emma",
                   "Frank", "Grace", "Henry", "Iris", "Jack", "Kate", "Liam",
                   "Mia", "Noah", "Olivia", "Paul", "Quinn", "Rose"]
    last_names = ["Smith", "Johnson", "Williams", "Brown", "Jones", "Garcia",
                  "Miller", "Davis", "Rodriguez", "Martinez", "Hernandez",
                  "Lopez", "Gonzalez", "Wilson", "Anderson", "Thomas"]
    return f"{random.choice(first_names)} {random.choice(last_names)}"


def _generate_insurance_id(fake=None) -> str:
    """Generate a fake insurance ID."""
    if fake and _FAKER_AVAILABLE:
        return fake.bothify("INS-####-??##").upper()
    prefix = "INS"
    num = random.randint(1000, 9999)
    letters = "".join(random.choices("ABCDEFGHIJKLMNOPQRSTUVWXYZ", k=2))
    suffix = random.randint(10, 99)
    return f"{prefix}-{num}-{letters}{suffix}"


def generate_patient_record(
    patient_id: Optional[str] = None,
    party: str = "party_a",
    fake=None
) -> Dict:
    """
    Generate a single synthetic patient record.

    All values are randomly generated within realistic medical ranges.
    The record is clearly marked as synthetic data.

    Args:
        patient_id: Optional custom patient ID. Auto-generated if None.
        party: Party identifier ("party_a", "party_b", "party_c").
        fake: Optional Faker instance for realistic names.

    Returns:
        Dictionary containing a complete patient record.
    """
    if patient_id is None:
        patient_id = f"{party.upper()}-P{random.randint(10000, 99999)}"

    diagnosis = random.choice(ICD10_CODES)
    age = random.randint(18, 90)

    # Correlate some values with age for realism
    bp_base = 110 + (age - 30) * 0.5
    glucose_base = 85 + (age - 30) * 0.3

    admission_date = datetime.now() - timedelta(days=random.randint(1, 365))

    return {
        "patient_id": patient_id,
        "name": _generate_name(fake),
        "age": age,
        "gender": random.choice(["M", "F", "Other"]),
        "blood_pressure_systolic": round(random.gauss(bp_base, 15), 1),
        "blood_pressure_diastolic": round(random.gauss(75, 10), 1),
        "glucose_level": round(random.gauss(glucose_base, 20), 1),
        "heart_rate": round(random.gauss(75, 12), 1),
        "cholesterol": round(random.gauss(200, 35), 1),
        "bmi": round(random.gauss(26, 4), 1),
        "diagnosis_code": diagnosis[0],
        "diagnosis_description": diagnosis[1],
        "insurance_id": _generate_insurance_id(fake),
        "admission_date": admission_date.strftime("%Y-%m-%d"),
        "party": party,
        "party_name": PARTY_NAMES.get(party, party),
        "is_synthetic": True,
        "data_label": "⚠️ SYNTHETIC DATA — NOT REAL PATIENT INFORMATION",
    }


def generate_party_records(
    party: str,
    count: int = 100,
    seed: Optional[int] = None
) -> List[Dict]:
    """
    Generate a batch of synthetic patient records for one party.

    Args:
        party: Party identifier ("party_a", "party_b", "party_c").
        count: Number of records to generate (default: 100).
        seed: Optional random seed for reproducibility.

    Returns:
        List of patient record dictionaries.

    Example:
        >>> records = generate_party_records("party_a", count=50, seed=42)
        >>> len(records)
        50
        >>> all(r["is_synthetic"] for r in records)
        True
    """
    if seed is not None:
        random.seed(seed)

    fake = Faker() if _FAKER_AVAILABLE else None
    if fake and seed is not None:
        Faker.seed(seed)

    records = []
    for i in range(count):
        pid = f"{party.upper().replace('PARTY_', 'P')}-{i+1:04d}"
        record = generate_patient_record(patient_id=pid, party=party, fake=fake)
        records.append(record)

    return records


def generate_all_parties(
    parties: int = 3,
    records_per_party: int = 100,
    seed: Optional[int] = 42
) -> Dict[str, List[Dict]]:
    """
    Generate synthetic datasets for all parties.

    Args:
        parties: Number of parties (default: 3, supports up to 26).
        records_per_party: Records per party (default: 100).
        seed: Random seed for reproducibility.

    Returns:
        Dictionary mapping party names to their record lists.

    Example:
        >>> data = generate_all_parties(parties=3, records_per_party=50)
        >>> len(data)
        3
        >>> all(len(records) == 50 for records in data.values())
        True
    """
    # Generate dynamic party IDs for any count
    party_ids = [f"party_{_PARTY_LETTERS[i]}" for i in range(min(parties, len(_PARTY_LETTERS)))]
    all_data = {}

    for i, party_id in enumerate(party_ids):
        party_seed = seed + i if seed is not None else None
        all_data[party_id] = generate_party_records(
            party_id, records_per_party, party_seed
        )

    return all_data


def save_party_data(
    data: Dict[str, List[Dict]],
    output_dir: str = "sample_data"
) -> Dict[str, str]:
    """
    Save party data as JSON files.

    Args:
        data: Dictionary of party → records from generate_all_parties().
        output_dir: Directory to save JSON files.

    Returns:
        Dictionary mapping party names to file paths.
    """
    os.makedirs(output_dir, exist_ok=True)
    file_paths = {}

    for party_id, records in data.items():
        filepath = os.path.join(output_dir, f"{party_id}_records.json")
        with open(filepath, "w") as f:
            json.dump({
                "party_id": party_id,
                "party_name": PARTY_NAMES.get(party_id, party_id),
                "record_count": len(records),
                "is_synthetic": True,
                "label": "⚠️ ALL DATA IN THIS FILE IS SYNTHETIC/FAKE",
                "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "records": records,
            }, f, indent=2)
        file_paths[party_id] = filepath

    return file_paths


def get_data_summary(data: Dict[str, List[Dict]]) -> Dict:
    """
    Generate summary statistics of the synthetic data.

    Args:
        data: Dictionary of party → records.

    Returns:
        Summary dictionary with aggregated statistics.
    """
    summary = {
        "total_records": 0,
        "parties": {},
        "is_synthetic": True,
    }

    for party_id, records in data.items():
        n = len(records)
        summary["total_records"] += n

        ages = [r["age"] for r in records]
        bps = [r["blood_pressure_systolic"] for r in records]
        glucoses = [r["glucose_level"] for r in records]

        summary["parties"][party_id] = {
            "name": PARTY_NAMES.get(party_id, party_id),
            "record_count": n,
            "avg_age": round(sum(ages) / n, 1),
            "avg_blood_pressure": round(sum(bps) / n, 1),
            "avg_glucose": round(sum(glucoses) / n, 1),
            "age_range": [min(ages), max(ages)],
            "diagnosis_distribution": _count_diagnoses(records),
        }

    return summary


def _count_diagnoses(records: List[Dict]) -> Dict[str, int]:
    """Count diagnosis code frequency in records."""
    counts = {}
    for r in records:
        code = r.get("diagnosis_code", "Unknown")
        counts[code] = counts.get(code, 0) + 1
    return dict(sorted(counts.items(), key=lambda x: x[1], reverse=True))
